import {defineApp,feature} from './domain-config.mjs';
export default defineApp({
  "id": "ai-ecommerce-fulfillment-inventory-loss-recovery",
  "engine": "recovery",
  "title": "Ecommerce Fulfillment Inventory-Loss Recovery",
  "shortTitle": "Ecommerce Fulfillment Inventory-Loss Recovery",
  "tagline": "Recover inventory value for inbound shortages, warehouse losses, damage, disposal, and incorrect reimbursements.",
  "industry": "Ecommerce Asset Recovery",
  "buyer": "Marketplace sellers and omnichannel retailers",
  "uiPort": 4732,
  "apiPort": 5732,
  "accent": "#0f766e",
  "currency": "USD",
  "primaryOutcome": "Ecommerce Fulfillment Inventory-Loss Recovery converted into governed, evidence-backed financial outcomes",
  "valueNarrative": "Connect fulfillment agreements, inbound shipments, receiving, inventory adjustments, warehouse events, damage, loss, removals, reimbursements, and settlements in one accountable workflow. Recover inventory value for inbound shortages, warehouse losses, damage, disposal, and incorrect reimbursements.",
  "calculation": {
    "actualKey": "receivedAmount",
    "expectedKey": "entitledAmount",
    "actualLabel": "Received or Recognized Amount",
    "expectedLabel": "Contract or Rule-Supported Entitlement",
    "varianceLabel": "Unrecovered supported value",
    "direction": "expected-minus-actual",
    "finding": "Ecommerce Fulfillment Inventory-Loss Recovery evidence indicates a measurable financial exception.",
    "actions": [
      "Validate the effective agreement, eligibility rules, and accountable parties",
      "Reconcile transaction-level operational and financial evidence",
      "Prepare the correction, recovery, or compliance package",
      "Track counterparty response, approval, cash, and preventive control closure"
    ]
  }
},[
feature("fulfillment-agreement-library","EFI01","Fulfillment agreement library","Execute fulfillment agreement library using fulfillment agreements, inbound shipments, receiving, inventory adjustments, warehouse events, damage, loss, removals, reimbursements, and settlements.","Produce a governed fulfillment agreement library decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Fulfillment Provider / SKU","text","Fulfillment Provider / SKU · Standard Case"],["caseReference","Fulfillment agreement library Reference","text","EFI01-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1731250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",2094813],["domainDriver","Loss Event","select","Inbound shortage",["Inbound shortage","Warehouse loss","Carrier damage"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Fulfillment agreement library case","SKU cost registry case","Inbound shipment ingestion case","Receiving reconciliation case","Inventory adjustment tracking case"]}),
feature("sku-cost-registry","EFI02","SKU cost registry","Execute sku cost registry using fulfillment agreements, inbound shipments, receiving, inventory adjustments, warehouse events, damage, loss, removals, reimbursements, and settlements.","Produce a governed sku cost registry decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Fulfillment Provider / SKU","text","Fulfillment Provider / SKU · Standard Case"],["caseReference","SKU cost registry Reference","text","EFI02-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1731250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",2094813],["domainDriver","Loss Event","select","Inbound shortage",["Inbound shortage","Warehouse loss","Carrier damage"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Fulfillment agreement library case","SKU cost registry case","Inbound shipment ingestion case","Receiving reconciliation case","Inventory adjustment tracking case"]}),
feature("inbound-shipment-ingestion","EFI03","Inbound shipment ingestion","Execute inbound shipment ingestion using fulfillment agreements, inbound shipments, receiving, inventory adjustments, warehouse events, damage, loss, removals, reimbursements, and settlements.","Produce a governed inbound shipment ingestion decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Fulfillment Provider / SKU","text","Fulfillment Provider / SKU · Standard Case"],["caseReference","Inbound shipment ingestion Reference","text","EFI03-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1731250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",2094813],["domainDriver","Loss Event","select","Inbound shortage",["Inbound shortage","Warehouse loss","Carrier damage"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Fulfillment agreement library case","SKU cost registry case","Inbound shipment ingestion case","Receiving reconciliation case","Inventory adjustment tracking case"]}),
feature("receiving-reconciliation","EFI04","Receiving reconciliation","Execute receiving reconciliation using fulfillment agreements, inbound shipments, receiving, inventory adjustments, warehouse events, damage, loss, removals, reimbursements, and settlements.","Produce a governed receiving reconciliation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Fulfillment Provider / SKU","text","Fulfillment Provider / SKU · Standard Case"],["caseReference","Receiving reconciliation Reference","text","EFI04-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1731250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",2094813],["domainDriver","Loss Event","select","Inbound shortage",["Inbound shortage","Warehouse loss","Carrier damage"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Fulfillment agreement library case","SKU cost registry case","Inbound shipment ingestion case","Receiving reconciliation case","Inventory adjustment tracking case"]}),
feature("inventory-adjustment-tracking","EFI05","Inventory adjustment tracking","Execute inventory adjustment tracking using fulfillment agreements, inbound shipments, receiving, inventory adjustments, warehouse events, damage, loss, removals, reimbursements, and settlements.","Produce a governed inventory adjustment tracking decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Fulfillment Provider / SKU","text","Fulfillment Provider / SKU · Standard Case"],["caseReference","Inventory adjustment tracking Reference","text","EFI05-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1731250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",2094813],["domainDriver","Loss Event","select","Inbound shortage",["Inbound shortage","Warehouse loss","Carrier damage"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Fulfillment agreement library case","SKU cost registry case","Inbound shipment ingestion case","Receiving reconciliation case","Inventory adjustment tracking case"]}),
feature("warehouse-loss-detection","EFI06","Warehouse loss detection","Execute warehouse loss detection using fulfillment agreements, inbound shipments, receiving, inventory adjustments, warehouse events, damage, loss, removals, reimbursements, and settlements.","Produce a governed warehouse loss detection decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Fulfillment Provider / SKU","text","Fulfillment Provider / SKU · Standard Case"],["caseReference","Warehouse loss detection Reference","text","EFI06-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1731250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",2094813],["domainDriver","Loss Event","select","Inbound shortage",["Inbound shortage","Warehouse loss","Carrier damage"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Fulfillment agreement library case","SKU cost registry case","Inbound shipment ingestion case","Receiving reconciliation case","Inventory adjustment tracking case"]}),
feature("damage-event-evidence","EFI07","Damage event evidence","Execute damage event evidence using fulfillment agreements, inbound shipments, receiving, inventory adjustments, warehouse events, damage, loss, removals, reimbursements, and settlements.","Produce a governed damage event evidence decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Fulfillment Provider / SKU","text","Fulfillment Provider / SKU · Standard Case"],["caseReference","Damage event evidence Reference","text","EFI07-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1731250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",2094813],["domainDriver","Loss Event","select","Inbound shortage",["Inbound shortage","Warehouse loss","Carrier damage"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Fulfillment agreement library case","SKU cost registry case","Inbound shipment ingestion case","Receiving reconciliation case","Inventory adjustment tracking case"]}),
feature("disposal-authorization-control","EFI08","Disposal authorization control","Execute disposal authorization control using fulfillment agreements, inbound shipments, receiving, inventory adjustments, warehouse events, damage, loss, removals, reimbursements, and settlements.","Produce a governed disposal authorization control decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Fulfillment Provider / SKU","text","Fulfillment Provider / SKU · Standard Case"],["caseReference","Disposal authorization control Reference","text","EFI08-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1731250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",2094813],["domainDriver","Loss Event","select","Inbound shortage",["Inbound shortage","Warehouse loss","Carrier damage"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Fulfillment agreement library case","SKU cost registry case","Inbound shipment ingestion case","Receiving reconciliation case","Inventory adjustment tracking case"]}),
feature("removal-order-matching","EFI09","Removal order matching","Execute removal order matching using fulfillment agreements, inbound shipments, receiving, inventory adjustments, warehouse events, damage, loss, removals, reimbursements, and settlements.","Produce a governed removal order matching decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Fulfillment Provider / SKU","text","Fulfillment Provider / SKU · Standard Case"],["caseReference","Removal order matching Reference","text","EFI09-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1731250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",2094813],["domainDriver","Loss Event","select","Inbound shortage",["Inbound shortage","Warehouse loss","Carrier damage"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Fulfillment agreement library case","SKU cost registry case","Inbound shipment ingestion case","Receiving reconciliation case","Inventory adjustment tracking case"]}),
feature("reimbursement-eligibility","EFI10","Reimbursement eligibility","Execute reimbursement eligibility using fulfillment agreements, inbound shipments, receiving, inventory adjustments, warehouse events, damage, loss, removals, reimbursements, and settlements.","Produce a governed reimbursement eligibility decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Fulfillment Provider / SKU","text","Fulfillment Provider / SKU · Standard Case"],["caseReference","Reimbursement eligibility Reference","text","EFI10-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1731250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",2094813],["domainDriver","Loss Event","select","Inbound shortage",["Inbound shortage","Warehouse loss","Carrier damage"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Fulfillment agreement library case","SKU cost registry case","Inbound shipment ingestion case","Receiving reconciliation case","Inventory adjustment tracking case"]}),
feature("replacement-cost-calculation","EFI11","Replacement cost calculation","Execute replacement cost calculation using fulfillment agreements, inbound shipments, receiving, inventory adjustments, warehouse events, damage, loss, removals, reimbursements, and settlements.","Produce a governed replacement cost calculation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Fulfillment Provider / SKU","text","Fulfillment Provider / SKU · Standard Case"],["caseReference","Replacement cost calculation Reference","text","EFI11-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1731250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",2094813],["domainDriver","Loss Event","select","Inbound shortage",["Inbound shortage","Warehouse loss","Carrier damage"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Fulfillment agreement library case","SKU cost registry case","Inbound shipment ingestion case","Receiving reconciliation case","Inventory adjustment tracking case"]}),
feature("provider-claim-generation","EFI12","Provider claim generation","Execute provider claim generation using fulfillment agreements, inbound shipments, receiving, inventory adjustments, warehouse events, damage, loss, removals, reimbursements, and settlements.","Produce a governed provider claim generation decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Fulfillment Provider / SKU","text","Fulfillment Provider / SKU · Standard Case"],["caseReference","Provider claim generation Reference","text","EFI12-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1731250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",2094813],["domainDriver","Loss Event","select","Inbound shortage",["Inbound shortage","Warehouse loss","Carrier damage"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Fulfillment agreement library case","SKU cost registry case","Inbound shipment ingestion case","Receiving reconciliation case","Inventory adjustment tracking case"]}),
feature("denial-appeal-workflow","EFI13","Denial appeal workflow","Execute denial appeal workflow using fulfillment agreements, inbound shipments, receiving, inventory adjustments, warehouse events, damage, loss, removals, reimbursements, and settlements.","Produce a governed denial appeal workflow decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Fulfillment Provider / SKU","text","Fulfillment Provider / SKU · Standard Case"],["caseReference","Denial appeal workflow Reference","text","EFI13-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1731250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",2094813],["domainDriver","Loss Event","select","Inbound shortage",["Inbound shortage","Warehouse loss","Carrier damage"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Fulfillment agreement library case","SKU cost registry case","Inbound shipment ingestion case","Receiving reconciliation case","Inventory adjustment tracking case"]}),
feature("cash-reimbursement-matching","EFI14","Cash reimbursement matching","Execute cash reimbursement matching using fulfillment agreements, inbound shipments, receiving, inventory adjustments, warehouse events, damage, loss, removals, reimbursements, and settlements.","Produce a governed cash reimbursement matching decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Fulfillment Provider / SKU","text","Fulfillment Provider / SKU · Standard Case"],["caseReference","Cash reimbursement matching Reference","text","EFI14-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1731250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",2094813],["domainDriver","Loss Event","select","Inbound shortage",["Inbound shortage","Warehouse loss","Carrier damage"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Fulfillment agreement library case","SKU cost registry case","Inbound shipment ingestion case","Receiving reconciliation case","Inventory adjustment tracking case"]}),
feature("provider-sku-analytics","EFI15","Provider SKU analytics","Execute provider sku analytics using fulfillment agreements, inbound shipments, receiving, inventory adjustments, warehouse events, damage, loss, removals, reimbursements, and settlements.","Produce a governed provider sku analytics decision with quantified value, accountable ownership, retained evidence, and measurable closure.",[["caseEntity","Fulfillment Provider / SKU","text","Fulfillment Provider / SKU · Standard Case"],["caseReference","Provider SKU analytics Reference","text","EFI15-2026-001"],["receivedAmount","Received or Recognized Amount","currency",1731250],["entitledAmount","Contract or Rule-Supported Entitlement","currency",2094813],["domainDriver","Loss Event","select","Inbound shortage",["Inbound shortage","Warehouse loss","Carrier damage"]],["evidenceState","Evidence State","select","Complete",["Complete","Incomplete","Exception"]],["reviewDeadline","Review Deadline","date","2026-10-31"]],{amountField:"receivedAmount",subjects:["Fulfillment agreement library case","SKU cost registry case","Inbound shipment ingestion case","Receiving reconciliation case","Inventory adjustment tracking case"]})
]);
